model:
  source: "huggingface"
  repo_id: "mandresyandri/yolov8_biolit_crop" #TODO: mettre sur le huggingFace dataforgood
  filename: "runs/biolit_v2_yolo_finetuned/best.pt" #TODO: mettre sur le huggingFace dataforgood

inference:
  conf: 0.4
  iou: 0.45
  imgsz: 640
  device: "cpu"
  save: true
  save_dir: "outputs/"

